### ISSUE TITLE
Latest syntax podcast isn't being pulled in

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#104]
Looks like the syntax API isn't working? https://syntax.fm/api/shows/latest 

Might need to be fixed on /wesbos/syntax instead

**Comment by manishkrjha** [comment]
Hey, Wes, I'd like to try this. Can you provide a little more details of what exactly is needed to be done? Apologies for bothering you but being a rookie I'm having little hard time in figuring out the issue.

Thanks in advance

**Comment by wesbos** [comment]
It's fixed over at the syntax repo :)
