### ISSUE TITLE
interested in contributing, what do you need?

### ISSUE THREAD

**Issue by serahkiburu** [wesbos/wesbos#114]
Hey, saw your tweet and I would like to spend some time in your repositor(ies), and invite others to contribute too if possible. Your tweet mentioned plenty, wondering if you can point to specific files the need attention i.e. what files need HTML to markdown conversion, etc?

**Comment by rishavjaiss** [comment]
Hey, how can i help you? Would love to.

**Comment by wesbos** [comment]
Hey! Thanskf or offering to help.

Some easy wins: https://github.com/wesbos/wesbos/search?q=%3Ch3%3E

Some of the blog posts were written in HTML, converting them to markdown would be great.
