### ISSUE TITLE
4xx client errors (Sitechecker)

### ISSUE THREAD

**Issue by ilyesrd** [wesbos/wesbos#154]
Below you see the list of URLs with 4xx status code. Sitechecker bot found these URLs because other pages on your website link to them.
<img width="1552" alt="Capture d’écran 2021-03-07 à 13 12 53" src="https://user-images.githubusercontent.com/25514080/110239362-d735d600-7f46-11eb-89a6-1352d64e8037.png">

**Comment by wesbos** [comment]
thanks - fixed these! Was a pagination issue for previous page on the first page
