### ISSUE TITLE
Workflows link on the /uses page links to a Not Found page

### ISSUE THREAD

**Issue by KlimekM** [wesbos/wesbos#156]
Hey Wes,

Not pressing at all, but figured you may want to know that the workflow link on https://wesbos.com/uses seems to be broken.

Link:
<img width="611" alt="Screen Shot 2021-04-23 at 10 51 27 PM" src="https://user-images.githubusercontent.com/15256554/115946454-e9cc8600-a486-11eb-8410-6b0694fec35d.png">

Points to: https://wes.io/fY7q

Lands on:
<img width="885" alt="Screen Shot 2021-04-23 at 10 52 19 PM" src="https://user-images.githubusercontent.com/15256554/115946469-0072dd00-a487-11eb-8fcd-f6513fd279c1.png">

I'd put in a PR, but not sure what the correct URL should be.

**Comment by wesbos** [comment]
fixed! Thanks
