### ISSUE TITLE
HSL on canvas

### ISSUE THREAD

**Issue by gpyne** [wesbos/wesbos#182]
Part 85 on Audio Visualization incorrectly states "we cannot use HSL on canvas".
The canvas context can accept any CSS color value. https://www.w3.org/TR/2dcontext/#fill-and-stroke-styles
i.e. The whole section on converting from HSL to RGB can be re/moved.

**Comment by wesbos** [comment]
@Asjas Can you add this note to the Course Notes for this video?

**Comment by Asjas** [comment]
@wesbos Added! 🙂
