### ISSUE TITLE
little misspell

### ISSUE THREAD

**Issue by etapic** [wesbos/wesbos#193]
path: wesbos/src/javascript/08-data-types/43-objects-references-to-values/43-objects-references-to-values.mdx 
Sentence: That is not the case for booleans, numbers and strings, but it is the case for objects and strings.
Should be: That is not the case for booleans, numbers and strings, but it is the case for objects and arrays.

**Comment by zachOS-tech** [comment]
This was fixed by PR #207

**Comment by wesbos** [comment]
thanks!
