### ISSUE TITLE
Order of plugin matters

### ISSUE THREAD

**Issue by alexluong** [wesbos/wesbos#2]
Hi Wes,

Excited to see you're using Gatsby for your new website.

Browsing through the code, I see that you commented `// Plugins are run concurrently so order does not matter`. In my experience, this is not entirely true as the sourcing function will run in the plugin order. These may be edge cases, but in some situation switching the order of some plugins will result in 2 different schemas.

I'd love to explain more about these edge cases if you're interested. Hope you don't mind my unsolicited comment. Looking forward to your new site, Wes.

https://github.com/wesbos/wesbos/blob/f11d4a71c77ab64e02863eedd3ab300476e1ab49/gatsby-config.js#L15

**Comment by wesbos** [comment]
hey thanks a ton - I was actually researching this and since I found they run concurrently, I assumed it didn't matter. I'd love to hear more about the edge cases :)

**Comment by alexluong** [comment]
For the most part, the order doesn't matter. But here are some edge cases I ran into recently while working with Gatsby.

### Sourcing nodes

So, the behavior of `gatsby-source-filesystem` is that every file can only be sourced once. Therefore, if we do something like this:

```js
plugins: [
  {
    resolve: "gatsby-source-filesystem",
    options: {
      name: "type-a",
      path: `${__dirname}/content`,
    },
  },
  {
    resolve: "gatsby-source-filesystem",
    options: {
      name: "type-b",
      path: `${__dirname}/content`,
     },
  },
]
```

Then every file in `/content` will be `type-a` and none will be `type-b`. If we switch the order of the plugin, everything will be `type-b` and none `type-a`.

### On create node

Another situation is that: the sourcing of nodes will take place in the order in the plugins array. And with every trigger of `sourceNode`, it will then trigger `onCreateNode`. So let's say you have 2 node types, `Course` and `Lesson`, and you're sourcing the lessons first. Then:

```js
exports.onCreateNode = ({ node, getNode }) => {
  if (node.internal.type === "lessons") {
    const course = goGetCourseNode(getNode)
    // this will result in an error
    // because course nodes haven't been created yet
  }
}
```

So, we'd have to switch the order and source courses first if we want to do something like this.
