### ISSUE TITLE
Mobile horz scroll

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#21]
![IMG_995AA33724C9-1](https://user-images.githubusercontent.com/176013/79489598-82fdcc80-7fe9-11ea-94ca-9bb930bf7dc1.jpeg)

**Comment by simeydk** [comment]
It's back :(

![image](https://user-images.githubusercontent.com/13088589/80019539-f7e47100-84d7-11ea-84de-96cf5604e8b2.png)
