### ISSUE TITLE
None of the Merged PR's Have Deployed Since 6/16

### ISSUE THREAD

**Issue by zachOS-tech** [wesbos/wesbos#263]
Hey Wes,

It looks like none of the PRs since June 16 have deployed on Netlify as it keeps erroring out when it tries to do the CI/CD

## Error Logs

Here is the link to the first deploy that started failing: https://app.netlify.com/sites/wesbos/deploys/60f85d8e5f8e3b0007a65a82

**Comment by raae** [comment]
It seems to be that gatsby-remark-embedder errors and stops the build when there is a broken embed link such as https://twitter.com/SelenIT2/status/499321739411996672.

**Comment by wesbos** [comment]
shoot eh, let me take a look into it, thanks!

**Comment by wesbos** [comment]
Fixed, also updated to Gatsby 4 :)

**Comment by raae** [comment]
Congrats, version 4 is so much fun 🥳
