### ISSUE TITLE
A little omission of word

### ISSUE THREAD

**Issue by rakeshblocks** [wesbos/wesbos#268]
In the post : https://wesbos.com/tagged-template-literals
There seems an omission of word : **string pieces** after the line "After the array of all the {here},".

![image](https://user-images.githubusercontent.com/92524707/137315892-ec04ca99-5f6a-476f-86e9-03329e9e23ec.png)

Thanks for the Article. Learnt a lot :)

**Comment by wesbos** [comment]
thank you - i fixed this post
