### ISSUE TITLE
Transferwise doesn't work anymore

### ISSUE THREAD

**Issue by shuttermuse** [wesbos/wesbos#294]
You can't withdraw to a Transferwise account anymore from a Canadian PayPal account. They just reverse the transaction and charge you a $20 fee for even trying. Then they tell you they don't "support virtual banks" even though they are quite happy to verify the bank account in the first place.

In most other markets they are either doing that or charging you the additional 3% fee, which invalidates the whole point of moving the money to Wise for a better exchange rate. Essentially it looks like PayPal have plugged the holes in their scheme and we're once again forced into their draconian system of hidden fees.

**Comment by wesbos** [comment]
Yikes. Did you try use Evolve Bank + Trust instead of transferwise?
