### ISSUE TITLE
I have a major issue

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#3]
What is the fix?!?!

**Comment by thecodingaviator** [comment]
The issue looks very serious and should be fixed ASAP 🤣

**Comment by wesbos** [comment]
Hahaha yes! Good eye

**Comment by StewartEthan** [comment]
After careful analysis of the video, it looks like it might have been a typo. You typed `kjhihiouyiuhiluhiluhiuh`, but based on the rest of the code I'm guessing you were going for `kjhihiouyiuhiluhilujioh`. Just a couple letters off, maybe try that and see if it fixes the problem?

**Comment by the94air** [comment]
The perfect template for how to open a poorly detailed issue. Not even reproduce!. and because you are the owner, I wish that someone at this moment can hack into GitHub or your account, close this issue, and exit :smiling_imp:. Nice TicTok though :smile:.

**Comment by Weilbyte** [comment]
oh you just forgot a semicolon

**Comment by zilahir** [comment]
@wesbos please close this issue, and if your issue still persist, please open a new one with a bit more detail. Thanks.

**Comment by mastef** [comment]
Add `//` to the beginning of the line, it fixed it for me

**Comment by thecodingaviator** [comment]
@mastef that doesn’t work on my machine tho. Are you sure it fixes it?

**Comment by mastef** [comment]
@thecodingaviator better check your machine for viruses

**Comment by thecodingaviator** [comment]
I installed every-issue-fixer yesterday. Could that be the problem?

**Comment by the94air** [comment]
Hmmm, this is just getting more ridiculous and I am receiving notifications about it. `kjhihiouyiuhiluhiluhiuh` isn't javascript. Okay!!

**Comment by thecodingaviator** [comment]
@the94air 
![image](https://user-images.githubusercontent.com/34807532/65368579-9ec20f80-dc60-11e9-97dd-8ae289ace62e.png)

**Comment by the94air** [comment]
Keep up!

**Comment by wesbos** [comment]
well folks
