### ISSUE TITLE
The /uses page is lacking TP information

### ISSUE THREAD

**Issue by jeroenheijmans** [wesbos/wesbos#321]
The `/contact` page promises a certain bit of information:

https://github.com/wesbos/wesbos/blob/2ec728e073c7ef03dc352a6d075045e1d38b498a/src/pages/contact.js#L28-L33

However, on [the `/uses` page](https://github.com/wesbos/wesbos/blob/master/src/posts/Uses/Uses.mdx) information about toilet paper is missing. Not even a brand is named.

Either adding the information (preferred, I think) to the "Other..." section of `/uses`, or removing the promise of said information from `/contact` seems like an appropriate fix?

PS. I [searched the issues list](https://github.com/wesbos/wesbos/issues?q=is%3Aissue+toilet+paper+) but no open or closed prior issue seemed to exist.

**Comment by wesbos** [comment]
Kirkland all day long
