### ISSUE TITLE
ogimage no longer working 

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#323]
serverless function is crashing.

https://wesbos.com/.netlify/functions/ogimage?title=Wes+Bos&amp;url=https%3A%2F%2Fwesbos.com%2F*

@Asjas Do you think you could take a look at this for me? Will DM you

**Comment by wesbos** [comment]
Just upgraded chrome-aws-lambda, and for that I need to stick puppeteer-core to 10.1.0 until this is merged: https://github.com/alixaxel/chrome-aws-lambda/pull/264

Not sure if that will fix it but worth a shot

**Comment by Asjas** [comment]
@wesbos I did a test in the browser console and I think `title` needs to be used instead of `url`? Unless `url` is used in the codebase and `title` is just an example you posted here.

This code here
```js
const link = url.searchParams.get('url');
```

needs to be 

```js
const link = url.searchParams.get('title');
```

![Untitled](https://user-images.githubusercontent.com/3828967/170285450-a02bf9b2-79db-4203-b8f9-2340566e2b26.png)

**Comment by Asjas** [comment]
Adding a debugger statement in Firefox does show that `location.href` exists.

![Untitled](https://user-images.githubusercontent.com/3828967/170286305-d2bfead2-44d2-4ee2-8212-7fd25eb8c1b7.png)

**Comment by wesbos** [comment]
just replace the `.netlify/functions/ogimage` with `thumbnail` on any of the ogimage urls

https://wesbos.com/thumbnail?title=Uses&url=http%3A%2F%2Flocalhost%3A8888%2Fuses&thumbnail=%2Fstatic%2F0005c028a536c87975eb84ae3d32ae57%2Faeron.jpg

Pretty sure thumbnail page is working fine, but look at this:

the URL: https://wesbos.com/.netlify/functions/ogimage?title=Uses&amp;url=https%3A%2F%2Fwesbos.com%2Fuses&amp;thumbnail=%2Fstatic%2F0005c028a536c87975eb84ae3d32ae57%2Faeron.jpg 

Blank

BUT if I change the URL to replace &amp; with &, it works:

https://wesbos.com/.netlify/functions/ogimage?title=Uses&url=https%3A%2F%2Fwesbos.com%2Fuses&thumbnail=%2Fstatic%2F0005c028a536c87975eb84ae3d32ae57%2Faeron.jpg

So I bet I am encoding the URL incorrectly. Give me 2 mins

**Comment by wesbos** [comment]
Seems to only twitter:

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwesbos.com%2Fuses

**Comment by wesbos** [comment]
ohhh maybe, what was the issue with that one again?

**Comment by Asjas** [comment]
The full HTTPS URL path was missing from the Twitter OG Image tag, only the relative path to the image was used.

**Comment by wesbos** [comment]
Ohhh yeah, I think this is formatted properly. IF you run `$(`[name="twitter:image"]`).content` on any page it should give you a URL, click it, and it renders. 

I just deployed a cache bust to the image to see if that fixes it

**Comment by wesbos** [comment]
It's working :D It was a cache bust!

<img width="684" alt="image" src="https://user-images.githubusercontent.com/176013/170293406-782da2b2-2898-4262-9895-b7e3134a87a6.png">

**Comment by Asjas** [comment]
Awesome! Haha 😄
