### ISSUE TITLE
Create a square twitter image

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#324]
The OG Image is rectangle, which works well for some use cases, but I noticed that Twitter is using a square size more often now. 

There has got to be a way to provide a secondary image for twitter that is square. 

I'd imagine the approach:

1. Make a media query or class for the thumbnail page so it looks good when square: https://wesbos.com/thumbnail/?title=Uses&url=https://wesbos.com/uses&thumbnail=%2Fstatic%2F0005c028a536c87975eb84ae3d32ae57%2Faeron.jpg
2. Pass some arg to the ogimage serverless function that takes a screenshot, so it will use square dimensions: `await page.setViewport()` 
3. Set custom meta tags for the new square image

**Comment by wesbos** [comment]
Maybe this is in vein, changing to summary_large_image will work instead? 

https://twitter.com/raae/status/1529478411067998209

Commit:

https://github.com/wesbos/wesbos/commit/49b7da5e7d33058f2731a96928e3a1186a646f75

only time will tell

**Comment by raae** [comment]
For others seeing this, here is the docs for [Twitter Summary Card with Large Image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image).

**Comment by wesbos** [comment]
wow, that was an easy fix! Sheesh, I should have done that two years ago

<img width="276" alt="Screen Shot 2022-05-25 at 11 13 08 AM" src="https://user-images.githubusercontent.com/176013/170296715-72c84f2b-6d77-47a0-a59d-2d83497767a3.png">
