### ISSUE TITLE
uses should be a page, not a blog post

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#36]

**Comment by justaddcl** [comment]
When the /uses link in the nav is clicked, it activate both the /uses and Blog nav links. 

However, if the user clicks into the Blog then clicks the Uses page blog entry, it only activates the Blog nav link. If the user then clicks the /uses nav link, it will again activate the /uses nav link in addition to the Blog nav link.

**Comment by wesbos** [comment]
thanks! all fixed

**Comment by justaddcl** [comment]
of course! hope it was helpful!
