### ISSUE TITLE
Ternary not working as expected

### ISSUE THREAD

**Issue by dimbak** [wesbos/wesbos#363]
Hi, 

[Page](https://wesbos.com/javascript/09-gettin-loopy/52-looping-and-iterating-reduce)

I tested this and for some reason the ternary 

`totals.shirt ? totals.shirt + 1 : totals.shirt = 1; `

is not adding 1 in the loop like this does

`totals.shirt = totals.shirt + 1 || 1;
`
I checked for any typos I may have but could not find any. My apologies if I am missing something.

**Comment by dimbak** [comment]
In the [next lesson](https://wesbos.com/javascript/09-gettin-loopy/53-looping-and-iterating-reduce-exercise/) this is how its written and it works
`counts[char] ? counts[char] = counts[char] + 1 : counts[char] = 1;`

so maybe its 

`totals.shirt ? totals.shirt = totals.shirt + 1 : totals.shirt = 1; `

**Comment by wesbos** [comment]
thanks - this is the correct code that has been updated:

```js
totals.shirt ? (totals.shirt += 1) : (totals.shirt = 1);
```
