### ISSUE TITLE
Broken link to latest Syntax episode

### ISSUE THREAD

**Issue by pedrosousa** [wesbos/wesbos#393]
I noticed that the `Listen now →` link in the website footer is not working... I thought there was a slash missing, but there's more to it.

https://github.com/wesbos/wesbos/blob/42448b9e78e157e8b945eb18779bf1c1e80a08e1/src/components/Podcast.js#L50

Current link:
`https://syntax.fmmiddleware-explained` 

Working link:
`https://syntax.fm/show/747/middleware-explained`

Suggested change in `wesbos/src/components/Podcast.js`:
```diff
- <a href={`https://syntax.fm${podcast.slug}`}>Listen Now → </a> 
+ <a href={`https://syntax.fm/show/${podcast.number}/${podcast.slug}`}>Listen Now → </a> 
```
(Not sure about using `podcast.number` versus `podcast.displayNumber`)

**Comment by wesbos** [comment]
Ah thank you - you are right! Mind sending a PR? No biggie if not

**Comment by pedrosousa** [comment]
Sure, I can create a PR. Just wanted to make sure the change made sense.
