### ISSUE TITLE
X in the nav aren't vertically aligned

### ISSUE THREAD

**Issue by wesbos** [wesbos/wesbos#66]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/176013/79986591-4b27d680-847a-11ea-88d8-e6a259685810.png">

**Comment by Push9828** [comment]
Can you give more info about it

**Comment by chrish-d** [comment]
@Push9828 the yellow X's aren't vertically centered against the nav (they should be sitting a bit further down)

**Comment by wesbos** [comment]
fixed it ha!
