### ISSUE TITLE
Can you further explain why-not-WordPress as promised?

### ISSUE THREAD

**Issue by davidbhayes** [wesbos/wesbos#67]
New site looks great :)

Your article https://wesbos.com/new-wesbos-website contains the sentence: "I had over a decade on WordPress and I still love it, but I'll explain why I left WP in just a second." 

I was so eager to read the story laid out explicitly of why the whole Gatsby/MDX/etc vision caused you to leave. But then you only mentioned WP one other time.

I think there's a clear narrative about "developer coolness" vs the "easy for a non-technical person to make an email popup appear" one can read as subtext in the article as written, but I'd love to read it in (explicit/overt) text in this article or in a different one. (This is not meant as trolling. I am just v curious to know more about your perceptions of the trade-offs on new-stack vs WP.) Thanks!

**Comment by wesbos** [comment]
Sorry for the delay on this - happy to answer any Qs you still have
