### ISSUE TITLE
Restore audio linked on JavaScript30 course

### ISSUE THREAD

**Issue by arthurdenner** [wesbos/wesbos#80]
Hey Wes! 👋 

Something silly, but [the link to the snap sound](https://github.com/wesbos/JavaScript30/blob/master/19%20-%20Webcam%20Fun/index.html#L40) from day 19 is broken since you've moved to the new website. I've tried to find the file but only found references to the same link.

 If possible, please put the audio on the new website or update the link on the starter file.
 
Thanks for all your content.

**Comment by wesbos** [comment]
Hey! I ended up updating the sound in the files to another URL. Thanks again!
